title: that's not my code
email: changmin7537@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  이것저것 정리하는 블로그 입니다.
baseurl: ""
url: ""
permalink: /:categories/:title

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude_from_localization: ['js', 'img', 'css']
parallel_localization: false